Repository GDG-PKNU-Fondant/fondant-frontend, pull requests merged in 2025-02, with the labels that each got.

#17 Feature/#13: 상품/상점 카드 컴포넌트 구현
  .eslintrc.json
  src/assets/icons/rate.svg
  src/components/Card/BaseCard/index.tsx
  src/components/Card/MarketCard/MarketCard.stories.tsx
  src/components/Card/MarketCard/MarketCard.test.tsx
  src/components/Card/MarketCard/index.tsx
  src/components/Card/ProductCard/ProductCard.stories.tsx
  src/components/Card/ProductCard/ProductCard.test.tsx
  src/components/Card/ProductCard/index.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/index.tsx
  src/mocks/handlers.ts
  src/types/Card.ts
  src/types/Carousel.ts
Labels: 💎 feature

#22 Fix/#21: BaseCardProps의 marketName 속성을 optional로 변경
  src/types/Card.ts
Labels: 🛠️ fix

#19 Feature/#11: Header 구현
  .yarn/install-state.gz
  package.json
  src/assets/icons/cart.svg
  src/assets/icons/notification.svg
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/Badge.test.tsx
  src/components/Badge/index.tsx
  src/components/Header/Header.stories.tsx
  src/components/Header/Header.test.tsx
  src/components/Header/index.tsx
  src/components/TabNavigator/TabNavigator.stories.tsx
  src/components/TabNavigator/TabNavigator.test.tsx
  src/components/TabNavigator/index.tsx
  src/components/TabNavigator/tabs.ts
  src/mocks/constants/mockTabs.ts
  src/stores/badgeState.ts
  src/stores/scrollState.ts
  src/types/Badge.ts
  src/types/Header.ts
  src/types/TabNavigator.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: 💎 feature

#26 Feature/#20: 하단 탭 내비게이터 구현
  .eslintrc.json
  .yarn/install-state.gz
  package.json
  src/App.tsx
  src/assets/icons/category.svg
  src/assets/icons/home.svg
  src/assets/icons/my.svg
  src/assets/icons/search.svg
  src/assets/icons/wish.svg
  src/components/BottomTab/BottomTab.stories.tsx
  src/components/BottomTab/BottomTab.test.tsx
  src/components/BottomTab/index.tsx
  src/components/BottomTab/tabs.ts
  src/pages/Category/index.tsx
  src/pages/Home/index.tsx
  src/pages/My/index.tsx
  src/pages/Search/index.tsx
  src/pages/Wish/index.tsx
  src/stores/bottomTabState.ts
  yarn.lock
Labels: 💎 feature

#30 Refactor/#29: 캐러셀 컴포넌트 리팩토링
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/Carousel.test.tsx
  src/components/Carousel/index.tsx
  src/mocks/constants/mockCarouselSlides.ts
  src/mocks/handlers.ts
Labels: 🚀 refactor

#34 Feature/#24: 상점 프로필 카드 구현
  src/assets/icons/heart.svg
  src/components/MarketProfileCard/MarketProfileCard.stories.tsx
  src/components/MarketProfileCard/MarketProfileCard.test.tsx
  src/components/MarketProfileCard/index.tsx
  src/components/PreviewCard/index.tsx
  src/mocks/constants/mockMarketProfiles.ts
  src/types/MarketProfileCard.ts
  src/utils/formatPeopleCount.ts
  tsconfig.app.json
  vite.config.ts
Labels: 💎 feature

#35 Feature/#33: 모바일 레이아웃 구성
  src/App.tsx
  src/components/BottomTab/index.tsx
  src/components/Header/index.tsx
  src/components/TabNavigator/index.tsx
  src/hooks/useScrollVisibility.ts
  src/pages/Home/index.tsx
  src/stores/layoutState.ts
  src/stores/scrollState.ts
  src/styles/tailwind.css
  tsconfig.app.json
  vite.config.ts
Labels: 💎 feature
