Repository GDG-PKNU-Fondant/fondant-frontend, pull requests merged in 2025-01, with the labels that each got.

#8 Chore/#7: SVG 파일을 리액트 컴포넌트로 사용할 수 있도록 설정
  .yarn/cache/@babel-types-npm-7.26.5-8e8f93f536-65dc14aa32.zip
  .yarn/cache/@rollup-pluginutils-npm-5.1.4-83ce21024f-dc0294580e.zip
  .yarn/cache/@svgr-babel-plugin-add-jsx-attribute-npm-8.0.0-026be9c2be-3fc8e35d16.zip
  .yarn/cache/@svgr-babel-plugin-remove-jsx-attribute-npm-8.0.0-c98774fd19-ff992893c6.zip
  .yarn/cache/@svgr-babel-plugin-remove-jsx-empty-expression-npm-8.0.0-bee2c7d451-0fb691b63a.zip
  .yarn/cache/@svgr-babel-plugin-replace-jsx-attribute-value-npm-8.0.0-bf8ed25593-1edda65ef4.zip
  .yarn/cache/@svgr-babel-plugin-svg-dynamic-title-npm-8.0.0-c534fda2ad-876cec8914.zip
  .yarn/cache/@svgr-babel-plugin-svg-em-dimensions-npm-8.0.0-de7e3b5c02-be0e2d3911.zip
  .yarn/cache/@svgr-babel-plugin-transform-react-native-svg-npm-8.1.0-9f7491cf96-85b434a575.zip
  .yarn/cache/@svgr-babel-plugin-transform-svg-component-npm-8.0.0-2e9be9c6ad-04e2023d75.zip
  .yarn/cache/@svgr-babel-preset-npm-8.1.0-0dca9b0e1b-3a67930f08.zip
  .yarn/cache/@svgr-core-npm-8.1.0-77cc138b8f-da4a12865c.zip
  .yarn/cache/@svgr-hast-util-to-babel-ast-npm-8.0.0-5d74d59e64-88401281a3.zip
  .yarn/cache/@svgr-plugin-jsx-npm-8.1.0-e2710753df-0418a97807.zip
  .yarn/cache/camelcase-npm-6.3.0-e5e42a0d15-8c96818a90.zip
  .yarn/cache/cosmiconfig-npm-8.3.6-a5566e2779-dc339ebea4.zip
  .yarn/cache/dot-case-npm-3.0.4-09675b5521-a65e351941.zip
  .yarn/cache/entities-npm-4.5.0-7cdb83b832-853f8ebd5b.zip
  .yarn/cache/error-ex-npm-1.3.2-5654f80c0f-c1c2b8b65f.zip
  .yarn/cache/estree-walker-npm-2.0.2-dfab42f65c-6151e6f982.zip
  .yarn/cache/is-arrayish-npm-0.2.1-23927dfb15-eef4417e3c.zip
  .yarn/cache/json-parse-even-better-errors-npm-2.3.1-144d62256e-798ed4cf33.zip
  .yarn/cache/lower-case-npm-2.0.2-151055f1c2-83a0a5f159.zip
  .yarn/cache/no-case-npm-3.0.4-12884c3d98-0b2ebc113d.zip
  .yarn/cache/parse-json-npm-5.2.0-00a63b1199-62085b17d6.zip
  .yarn/cache/path-type-npm-4.0.0-10d47fc86a-5b1e2daa24.zip
  .yarn/cache/picomatch-npm-4.0.2-e93516ddf2-a7a5188c95.zip
  .yarn/cache/snake-case-npm-3.0.4-67f447c30d-0a7a79900b.zip
  .yarn/cache/svg-parser-npm-2.0.4-1b0b6afbe9-b3de665304.zip
  .yarn/cache/vite-plugin-svgr-npm-4.3.0-ded8bb690b-9ade316f20.zip
  .yarn/install-state.gz
  package.json
  tsconfig.app.json
  vite.config.ts
  yarn.lock
Labels: ☕️ chore

#10 Config/#3: Mock Service Worker 설치 및 설정
  .eslintrc.json
  .yarn/install-state.gz
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/mocks/server.ts
  tsconfig.app.json
  tsconfig.eslint.json
  vite.config.ts
  vitest.setup.ts
  yarn.lock
Labels: ⚙️ config

#12 Feature/#4: 캐러셀 구현
  index.html
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/Carousel.test.tsx
  src/components/Carousel/index.tsx
  src/mocks/handlers.ts
  src/styles/tailwind.css
  src/types/CarouselSlide.ts
  tailwind.config.js
  tsconfig.app.json
  vite.config.ts
  vitest.setup.ts
Labels: 💎 feature
